version: '3.8'

services:
  web:
    volumes:
      - ${AZURACAST_DATA_BASE}/stations:/var/azuracast/stations
      - ${AZURACAST_DATA_BASE}/backups:/var/azuracast/backups
      - ${AZURACAST_DATA_BASE}/db_data:/var/lib/mysql
      - ${AZURACAST_DATA_BASE}/www_uploads:/var/azuracast/storage/uploads
      - ${AZURACAST_DATA_BASE}/shoutcast2_install:/var/azuracast/storage/shoutcast2
      - ${AZURACAST_DATA_BASE}/stereo_tool_install:/var/azuracast/storage/stereo_tool
      - ${AZURACAST_DATA_BASE}/rsas_install:/var/azuracast/storage/rsas
      - ${AZURACAST_DATA_BASE}/geolite_install:/var/azuracast/storage/geoip
      - ${AZURACAST_DATA_BASE}/sftpgo_data:/var/azuracast/storage/sftpgo
      - ${AZURACAST_DATA_BASE}/acme:/var/azuracast/storage/acme
